### ISSUE TITLE
Client Node scanner pods don't get scheduled to “full” nodes

### ISSUE THREAD

**Issue by ET-Torsten** [mondoohq/mondoo-operator#1069]
I'm not sure if that is a feature request or if we are just missing something. 

We are trying to get Mondoo client node scanner to work. Operator installation worked fine and node scanner cron jobs were created. However, what happens now is that only 12 out of 20 node scanners can run because the rest are not schedule able on the nodes (too many pods, not enough resources etc.) 

The result is a “broken” implementation on Mondoo site because node scanners cannot run. 

Is there a way to force scheduling of the Node Scanners, like setting a priority class or something similar? 

Any assistance is appreciated.

**Comment by ET-Torsten** [comment]
> We are currently discussing a new feature: adding an option for node scanning as a DaemonSet. Would this also help with scheduling in your cluster?

Together with a priorityClass option, to guarantee scheduling, DeamonSets would be great. So we don't have to reschedule on starting crojobs. 

> We currently do not have an option like a priority class or something similar.
So for the Moment, we will disable the node scanner then and keep an eye on the new features that are coming. 

Thanks for your help @czunker

**Comment by imilchev** [comment]
this is addressed in #1076

**Comment by imilchev** [comment]
fixed with mondoo-operator v1.22.0. You can now specify the node scan style in the `MondooAuditConfig`
