### ISSUE TITLE
Scan API cannot access file

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#1091]
**Describe the bug**
The cnspec logs show these errors from time to time:
```
ERR error encountered while scanning stdout error="read |0: file already closed"
```

**To Reproduce**

??? Need to figure this out.

2. Select '....'
4. Note the error

**Expected behavior**
The file should still be available when accessed or not accessed when no longer needed.

**Desktop (please complete the following information):**

- cnspec 10.8.4
- mondoo-operator v1.21.1

**Comment by imilchev** [comment]
fixed in mondoohq/cnquery#3775
