### ISSUE TITLE
all resources managed by mondoo operator are missing required resources (cpu limits and memory)

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#133]
**Describe the bug**
The mondoo-client Pods created by the Deployment and DaemonSet are running without resources.
This triggers some of the mondoo policies.

**To Reproduce**
1. Install mondoo-operator version 0.0.9
2. Wait for Deployment and DaemonSet to be created
3. Check for resources in spec, e.g.,
`kubectl get deployment.apps/mondoo-client -o yaml | grep -i resources` and
`kubectl get daemonset.apps/mondoo-client -o yaml | grep -i resources`

**Expected behavior**
I would expect both to have resources defined.

As an example:
On our cluster the client consumed ~1.25 CPUs and ~450MB memory.

**Kubernetes**

OS: Ubuntu 20.04
Version mondoo-operator 0.0.9
Kubernetes version: 1.22.5

**Comment by chris-rock** [comment]
Great suggestion @czunker. In addition to the resource limits, we should also add proper health checks for the pods

**Comment by harshaisgud** [comment]
@czunker Is the resource consumption listed by you for all of the running mondoo pods including the operator or a specific pod?

**Comment by czunker** [comment]
@harshaisgud The example was only for the mondoo client running the cluster scan.

The client running inside the daemon set to scan the nodes, consumes the same amount of memory, but only a fraction of the CPU. Way below 0.1 CPU.

The mondoo operator consumes below 0.1 CPU and ~30MB memory.

**Comment by harshaisgud** [comment]
@czunker Thank you for the insights!
