### ISSUE TITLE
Add health checks to the Deployments/DaemonSets

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#140]
Allow the Pod to report on its own health via the Pod's health checks. The first thing that comes to mind is the ability to report unhealthy when the credentials are invalid.

It is possible to define a command that should be run inside the Pod if a simple HTTP endpoint is not feasible https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes 

Then use the status of the Deployments/DaemonsSets to report an overall Status into the MondooAuditConfig CR.

**Comment by chris-rock** [comment]
That requires mondoo client to expose the health check. For now we should go with the proposal in #63 where we run the mondoo status command.

**Comment by joelddiaz** [comment]
Yes. Closing this as this is already covered in #63
