### ISSUE TITLE
Report overall status into the MondooAuditConfig CR

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#141]
Start with extending the MondooAuditConfigStatus to hold fields where the mondoo-operator can report status based on the health of the deployed DaemonSets/Deployments.

A first implementation should at least be able to check that the Deployment and DaemonSet are Ready/Running. Something like the golang equivalent of:

```
jdiaz@joels-air mondoo-operator % kubectl get deployment -n mondoo-operator-system mondoo-client -o json | jq -r '.status.conditions[] | select(.type=="Available") | .status'        
True
```

And for the DaemonSet `kubectl get daemonset -n mondoo-operator-system mondoo-client -o json | jq -r .status.desiredNumberScheduled` should equal `.status.numberReady`.
 
And if all the Deployments and DaemonSets are healthy, then bubble that up as a high-level MondooAuditConfig.Status when all items are healthy. If a single one is unhealthy, then the entire status should reflect the unhealthy state.

```
// MondooAuditConfigStatus defines the observed state of MondooAuditConfig
type MondooAuditConfigStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Nodes store the name of the pods which are running mondoo instances
	Pods []string `json:"pods,omitempty"`

        OverallStatus string `json:"overallStatus,omitempty"`
}
```
The `OverallStatus` can be limited to a the options of Healthy or Degraded.

Perform fine-grained report for the individual items being monitored by using Conditions in the MondooAuditConfig.Status similar to what you find in a Deployment:

```
jdiaz@joels-air mondoo-operator (validating-webhook *) % kubectl get deployment -n mondoo-operator-system mondoo-client -o json | jq -r .status.conditions
[
  {
    "lastTransitionTime": "2022-03-04T17:18:34Z",
    "lastUpdateTime": "2022-03-04T17:18:34Z",
    "message": "Deployment has minimum availability.",
    "reason": "MinimumReplicasAvailable",
    "status": "True",
    "type": "Available"
  },
  {
    "lastTransitionTime": "2022-03-04T17:18:32Z",
    "lastUpdateTime": "2022-03-04T17:18:34Z",
    "message": "ReplicaSet \"mondoo-client-5b6cff55f9\" has successfully progressed.",
    "reason": "NewReplicaSetAvailable",
    "status": "True",
    "type": "Progressing"
  }
]
```

This would be something like type=NodeScanningAvailable with a status of True/False based on that individual component health.
And a type=APIScanningAvailable for the API scanning Deployment, etc. More specifically follow the k8s format with a struct to hold the condition results that looks like:
```
type MondooAuditConfigCondition struct {
	// Type is the specific type of the condition
	// +kubebuilder:validation:Required
	// +required
	Type AudicConfigConditionType `json:"type"`
	// Status is the status of the condition
	// +kubebuilder:validation:Required
	// +required
	Status corev1.ConditionStatus `json:"status"`
	// LastProbeTime is the last time we probed the condition
	LastProbeTime metav1.Time `json:"lastProbeTime,omitempty"`
	// LastTransitionTime is the last time the condition transitioned from one status to another.
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`
	// Reason is a unique, one-word, CamelCase reason for the condition's last transition
	Reason string `json:"reason,omitempty"`
	// Message is a human-readable message indicating details about the last transition
	Message string `json:"message,omitempty"`
}
```

An example where the node scanning is healthy, and the API scanning is unhealthy would look like:
```
jdiaz@joels-air mondoo-operator % kubectl get mondooauditconfig -n mondoo-operator-system mondoo-client -o json | jq -r .status.conditions
[
  {
    "lastTransitionTime": "2022-03-04T17:18:34Z",
    "lastUpdateTime": "2022-03-04T17:18:34Z",
    "message": "Node scanning deployed successfully.",
    "reason": "DaemonSetHealthy",
    "status": "True",
    "type": "NodeScanningAvailable"
  },
  {
    "lastTransitionTime": "2022-03-04T17:18:32Z",
    "lastUpdateTime": "2022-03-04T17:18:34Z",
    "message": "API scanning deployment degraded.",
    "reason": "Desired replicas not equal to running replicas.",
    "status": "False",
    "type": "APIScanningAvailable"
  }
]
```

Some concrete examples of the kinds of things we would want a condition for:
1. If the user tries to enable metrics reporting, but the Prometheus CRDs are not installed on the cluster

**Comment by chris-rock** [comment]
depends on health checks being implemented for pods https://github.com/mondoohq/mondoo-operator/issues/63
