### ISSUE TITLE
Implement system to allow publishing 'stable' container tags in addition to 'latest'

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#142]
Extend the MondooAuditConfig CRD to allow specifying something besides mondoo:latest ( https://hub.docker.com/r/mondoolabs/mondoo/tags ). In addition to being able to specify tags like 5.28.0 and 5.29.1, allow specifying a moving target like 'stable'.

The default ImagePullPolicy for any container tag not named 'latest' is to be set to 'IfNotPresent'. A node that has once pulled down mondoo:stable would never need to re-pull the container image as long as it remains cached on the node which it is scheduled on. Using a PullPolicy of 'Always' helps a bit, but doesn't solve the situation where the mondoo:stable tag points to a new container image as the Pod will not get restarted if there are no changes to the Pod.Spec.

For the case where a container is using a non-'latest' tag, have the mondoo-operator fetch the SHA of the container image and populate the Deployment/DaemonSet image with the specific container image. This will force a Pod to get rescheduled/updating whenever the container pointed to by 'stable' is updated.

Update the mondoo-operator to ensure that it periodically runs through the full Reconcile() loop (daily?) so that it can fetch the SHA and apply any needed updates to the Deployment/DaemonSets whenever the container image changes.

Something like `return ctrl.Result{Requque: true, RequeueAfter: time.After(time.Now() + time.Day)`

**Comment by chris-rock** [comment]
We are going to use https://github.com/google/go-containerregistry as the library to gather the required information

**Comment by chris-rock** [comment]
code to get the ref:

```go
desc, err := remote.Get(ref, remoteOpts...)
imgDigest := desc.Digest.String()
repoName := ref.Context().Name()
imageUrl := repoName + "@" + imgDigest
```
