### ISSUE TITLE
Write test cases for node scanning functions

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#162]
Similar to how the webhook setup functions have test cases in https://github.com/mondoohq/mondoo-operator/blob/main/controllers/webhooks_test.go , follow that pattern to write up test cases for the code in https://github.com/mondoohq/mondoo-operator/blob/main/controllers/nodes.go

**Comment by jensgrnb** [comment]
Operator-sdk uses a framework called ginkgo for testing: https://sdk.operatorframework.io/docs/building-operators/golang/testing/

As far as I can see this is being used in controllers/webhooks_test.go.

**Comment by joelddiaz** [comment]
The tests in webhooks_tests.go is more of a custom set of test cases using just the "fake" controller-runtime client, and the "testify" packages.
I'm not opposed to using ginko. Just using testify directly is what I've previously used.

**Comment by joelddiaz** [comment]
Ginkgo sounds good to me 👍
