### ISSUE TITLE
Code uniformness

### ISSUE THREAD

**Issue by jensgrnb** [mondoohq/mondoo-operator#181]
**What is is not working as you expected it?**

1. 
controllers/webhooks.go uses a .yaml manifest as base for it's objects, parses the .yaml in go and does the manipulation. 
controllers/nodes.go, workloads.go uses a method to return the base objects directly from the k8s go modules. 

We should stick to one.

2. 
The client.Get() method call in controllers/webhooks.go diverges from the standard used in controllers/nodes.go, workloads.go. 
We experienced this issue in the beginning as well, but found later that there was no need to diverge from the standard syntax:
https://github.com/mondoohq/mondoo-operator/issues/49

**Where on the platform does it happen?**
na

**How do we replicate the issue?**
na

**Expected behavior (i.e. solution)**
Code uniformness

**Comment by joelddiaz** [comment]
For 1 on the list above, we absolutely could remove the Service and Deployment from that `webhook-manifests.yaml` file (and build those resources in the code itself), but the other  resource (the ValidatingWebhookConfiguration) is a generated file based on lines in the source like https://github.com/mondoohq/mondoo-operator/blob/main/pkg/webhooks/core/webhook.go#L12 , which I'm not sure how to resolve for something that is generated for us.

For 2, client.ObjectKeyFromObject() returns a types.NamespacedName which appears to be what is used in nodes.go and workloads.go. The ObjectKeyFromObject() function just saves some extra typing, but accomplishes the exact same result https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L30-L36 when you already have a runtime.Object with the ObjectMeta pieces populated. But again, we can certainly change it to the approach where we fill out types.NamespacedName to have some more uniformity.

**Comment by jensgrnb** [comment]
Runtime generated files are I guess okay, but for the two other points I think we should try and get the webhooks.go closer to nodes.go and workloads.go. 

The same goes for the unit testing. If we can do it with Ginkgo I think we should.

**Comment by chris-rock** [comment]
Nothing to do here for now since web hooks work differently. `controllers/webhooks.go` uses auto-generated manifest that is only slightly changed. Nodes and Workload make more sense to stay in go structs since we derive a lot of data dynamically. 

As for testing, for sure we are using the same test framework.

**Comment by jensgrnb** [comment]
We are not using the same test framework currently, as we rely on both ginkgo and testify. Ginkgo we inherited from operator-sdk. 

in 1. I'm not referring to auto-generated manifests on webhooks.go's side, I'm referring to the controllers/webhook-manifests.yaml file that's read at runtime to populate the webhook-manager object. In Nodes.go and workloads.go these objects are instantiated from the go packages directly.

**Comment by joelddiaz** [comment]
I've put together a PR to move the webhook Service and Deployment resources from the YAML files to golang types in #216
