### ISSUE TITLE
Allow bypassing image/tag resolution

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#197]
In the event that DockerHub (or whatever container registry is being pulled from) is down. The mondoo-operator will error while setting up Deployments/DaemonSets.
Allow skipping the image/tag fetching via a global mondoo-operator config setting (perhaps using the MondooOperatorConfig CRD).

**Comment by chris-rock** [comment]
This should be added to the new MondooOperatorConfigSpec:

```
type MondooOperatorConfigSpec struct {
        Metrics Metrics `json:"metrics,omitempty"`
        SkipContainerResolution bool `json:"skipContainerResolution,omitempty"`
}
```

**Comment by harshaisgud** [comment]
@chris-rock  From what I understand if `SkipContainerResolution` is set to true, then images are pulled from Mondoo public dockerhub instead of the upstream mentioned. Is that correct?

**Comment by joelddiaz** [comment]
> No, this is about https://github.com/mondoohq/mondoo-operator/blob/main/controllers/utils.go#L41-L60. Every image resolve step requires a connection to the container registry. If the registry is down the operator will fail. This allow users to prevent resolving the digest.

Right, this is about taking either the default mondoo:latest image if the user hasn't set any image/tag overrides (without trying to get the sha), or using the overridden image/tag (without trying to get the sha).
