### ISSUE TITLE
Audit mondoo-operator for unnecessary early exits

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#199]
There are some places in the codepaths where an exit is made with a Requeque = true set.
In many cases this isn't needed and the Reconcile() can continue normally.

For example in a sequence like https://github.com/mondoohq/mondoo-operator/blob/main/controllers/nodes.go#L64-L70 , it is okay to continue forward and create/update the DaemonSet if needed. The DaemonSet/Pod should be unable to run if any volume that it needs to mount in isn't defined. Once the ConfigMap/volume appears, the DaemonSet/Pod should launch successfully.

While in general the Requeue set to true is harmless, the Reconcile() loops do make API calls to remote registries to resolve the SHA256, and the early exits from the Reconcile() cause more registry API calls than is strictly necessary.

**Comment by jensgrnb** [comment]
To reduce api calls we should just slow down the requeue when needed. The operator-sdk's scaffolding is meant to be used with requeue statements to make the code declarative.

**Comment by joelddiaz** [comment]
If we want to keep the manual requeues  (which I agree are supposed to be completely safe as the Reconcile() loop is meant to be idempotent), then perhaps it makes sense to cache the image:tag SHAs. And only try to resolve a new SHA if the age of the previous image/SHA is older than X amount of time.

My primary concern here is with the mondoo-operator making more API calls to the container registry than is really necessary. In the same way that we wouldn't want to restart the Reconcile() loop if we were making AWS API calls (as AWS API calls are definitely throttled beyond some (admittedly) high limit), the mondoo-operator should still be a good citizen and avoid making an excessive number of external API calls if possible.

**Comment by imilchev** [comment]
fixed with #361
