### ISSUE TITLE
Create a GitHub release for 0.2.0 with release notes

### ISSUE THREAD

**Issue by tas50** [mondoohq/mondoo-operator#206]
Even though 0.2.0 is tagged, 0.0.13 is the latest release showing in the releases sidebar for this repo. We need to make sure to draft a release for the tag and get release notes added.

Current releases:
![image](https://user-images.githubusercontent.com/1015200/159353873-af643a18-c993-4204-9be7-e491667dfc30.png)

**Comment by chris-rock** [comment]
That is because the release is still in progress

<img width="844" alt="Screenshot 2022-03-21 at 21 02 32" src="https://user-images.githubusercontent.com/1178413/159354450-0df983f0-d634-4f7b-b41c-8cadd4de2a15.png">
