### ISSUE TITLE
Update release.sh to include "previous version" information

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#207]
Today the release.sh script takes two parameters. The first is for the version of the mondoo-operator, and the second is for the version of the helm chart.

With the release of 0.2.0, we are synchronizing the operator version and the helm chart version.

Simplify the release.sh to accept only a single new "version" parameter that will serve to populate both the mondoo-operator data and the helm chart data.

Additionally, the releaes.sh script should be updated to receive a new paramter to use for filling out the "replaces" field on the OperatorHub ClusterServiceVersion.

When releasing an update to an existing operator into OperatorHub while using 'replaces-mode', we need to populate the 'replaces' field on the ClusterServiceVersion. Update the ClusterServiceVersion template so that release.sh can update the ClusterServiceVersion with the previous mondoo-operator version.

When complete, an invocation of release.sh should look like:
./release.sh 0.1.PREV 0.1.NEW

The generated bundle's ClusterServiceVersion should have the 'replaces' field set to 0.1.PREV.

```
jdiaz@joels-air mondoo-operator  % yq '.spec.replaces' ./bundle/manifests/mondoo-operator.clusterserviceversion.yaml 
0.1.PREV
```

**Comment by czunker** [comment]
Already fixed by https://github.com/mondoohq/mondoo-operator/pull/238
