### ISSUE TITLE
Cache go modules and images

### ISSUE THREAD

**Issue by jensgrnb** [mondoohq/mondoo-operator#219]
**Is your feature request related to a problem? Please describe.**
To speed up the CI we need some caching of the build dependencies. The lowest hanging fruit seem to be the go modules.

**Describe the solution you'd like**
Cached dependencies on the github runner

**Comment by harshaisgud** [comment]
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching Something similar to this
