### ISSUE TITLE
name DaemonSet and Deployment to reflect their purpose

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#242]
Presently, the names of the DaemonSet and Deployment are just "mondoo-client". The Pods created for the DaemonSet/Deployment both have prefixes of "mondoo-client" which makes it unclear which Pod is doing what.

Name the DaemonSet/Deployments so that their purpose is clear and the Pods are more easily distinguishable. Additionally, include the name of the MondooAuditConfig into the names for these objects to allow multiple MondooAuditConfigs to exist in the same Namespace.
 
DaemonSet name should be: MONDOO_AUDIT_CONFIG_NAME-node
Deployment for workloads/api scanning should be: MONDOO_AUDIT_CONFIG_NAME-api

~~Lastly, update the name of the Deployment for the webhook to also include MONDOO_AUDIT_CONFIG_NAME as the prefix.~~ (Covered as part of #252 )

Be sure to clean up any previous Deployment/DaemonSet to cover the case of someone upgrading from a previous version of the mondoo-operator to this new naming scheme so that we don't leak resources.

**Comment by imilchev** [comment]
I did add labels to these to distinguish them in #262. I do agree that the names should become more descriptive as well
