### ISSUE TITLE
restore e2e test for non-default namespace

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/mondoo-operator#280]
The original e2e test for non-default namespaces was set up to run the mondoo-operator in the `mondoo-operator` namespace, and create a MondooAuditConfig in a Namespace that wasn't `mondoo-operator`.

With the implementation of the new go-based e2e tests, the non-default test case actually runs the mondoo-operator and the MondooAuditConfig in the `some-namespace` Namespace.

While running the mondoo-operator itself in a different Namespace is also a useful thing to be able to validate, we should restore the test where mondoo-operator runs in one Namespace and the MondooAuditConfig is created in a different namespace.

**Comment by imilchev** [comment]
Oh, I completely misread the tests then. This would even simplify and speed up the integration tests because now we need to install the operator once. Then we just test the correct reconciliation of the audit config in 2 separate namespaces.
