### ISSUE TITLE
Add integration test for operator upgrade

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#322]
Add an integration test that deploys the current released version of the operator on github and then applies the local version. The goal is to verify that upgrade works. We don't have to create an extensive test that verifies everything but at least a check that the operator starts and that all changes are applied without errors.

**Comment by czunker** [comment]
Wait for https://github.com/mondoohq/mondoo-operator/pull/408.
 This includes some enhancements for the integration tests.
