### ISSUE TITLE
Missing OLM releases

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#346]
I noticed that some version are missing from the OLM repo. Not sure if it is intentional or not and that's why I haven't opened a PR for the latest version (v0.2.12). @joelddiaz please verify what should happen and close this issue

**Comment by joelddiaz** [comment]
There's no requirement that every version is released to OLM. In fact, we had a bad build that was failing their testing, so by definition, that version would never show up on OLM. The thing to keep in mind though, is when running the `release.sh` script, to set the previous-version to the last version released to OLM.
