### ISSUE TITLE
add integration mrn label to all assets discovered with operator

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/mondoo-operator#354]
looking forward to support the integrations screen that was in our internal demos today, we should ensure all k8s assets are labelled with `mondoo.com/integration-mrn` and the integration mrn they are attached to

this will allow us to filter the assets list to the assets that are part of the integration mrn/allow us to display the numbers needed for those

**Comment by joelddiaz** [comment]
@vjeffrey up until now our prefix for the Mondoo labels has been 'k8s.mondoo.com'. Just want to double-check whether you really want this new integration MRN label to be 'mondoo.com/integration-mrn'` or to follow the existing pattern with '***k8s***.mondoo.com/integration-mrn'?

**Comment by vjeffrey** [comment]
i'm thinking that for the sake of consistency/easy filtering, we would want it to be the mondoo.com/integration-mrn (this is what aws integrations use today, and how we do the "see your asset scores" button on the aws integration - its just a link to the list of assets with that tag filter applied) so thinking about the full integrations page, im guessing it would be easier for the ui/graphql users if we keep that tag consistent across all the integrations

totally open to hearing others' thoughts on that tho? maybe we want to separate labels by service more going forward?

**Comment by joelddiaz** [comment]
Consistency makes sense to me 👍
