### ISSUE TITLE
Deadlock when upgrading the operator to v0.4.1

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#406]
The v0.4.1 of the operator adds the feature for checking whether all `MondooAuditConfig` have been reconciled by the latest version. However, this result in a deadlock if the user already has an older version of the operator running in the cluster. We use leader election to make sure there is only 1 operator instance actively reconciling CRDs. If we upgrade a running operator the old version of the operator will be active until the pod with the new version becomes ready. In order for the new pod to be come ready it needs the lock to be released by the old version so it can actually reconcile the CRDs.

**Comment by czunker** [comment]
For the moment we decided on removing the version check from the readiness check.
But we will keep the version number in the `Status` field.

We will also update the docs, so the user knows how to use the field during updates.

In a future version we might add the version check back to the readiness check, but with this situation in mind.
