### ISSUE TITLE
Scan API Pod hangs in `Pending`

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#442]
**Describe the bug**
When for whatever, e.g., update, a second Scan API Pod is scheduled, while the first one is still running, the second hangs in `Pending`.

Error message for the second Pod:
```
0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.
```
This only happens in small clusters, e.g., minikube.

**To Reproduce**
1. Deploy the operator with k8s resource scanning enabled
2. Change the Deployment for the Scan API.
3. Describe newly created Pod of Scan API.

**Expected behavior**
Pod should schedule.

**Screenshots**
-

**Additional context**
Here is the Pod Anti-Affinity declared:
https://github.com/mondoohq/mondoo-operator/blob/main/controllers/scanapi/resources.go#L185

The same problem will exist for the admission webhook:
https://github.com/mondoohq/mondoo-operator/blob/84b0eec00330265bed8212fdba52158b2d0ddcdb/controllers/admission/resources.go#L175

We could change `RequiredDuringSchedulingIgnoredDuringExecution` to `PreferredDuringSchedulingIgnoredDuringExecution`.

**Comment by imilchev** [comment]
Changing to `PreferredDuringSchedulingIgnoredDuringExecution` makes sense. We shouldn't use `RequiredDuringSchedulingIgnoredDuringExecution` as this would, indeed, mean single-worker clusters won't work
