### ISSUE TITLE
Different resource requirements for container image scanning

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#456]
We should differentiate between cluster scanning and cluster scanning with container image scanning enabled. What I observed during my tests is that a simple cluster scan or admission controller scanning uses <150MB of RAM. However, a container image scan for a cluster with decent sized images can occasionally use up to 200MB and that is if the scan doesn't overlap with a cluster scan or an admission controller scan request.

I think the easiest way to address this is to make sure we provide higher default resource requests and limits whenever the container image scanning is enabled. We should allocate at least 250MB requests and put the limit to 500MB. With the current limits I noticed the scan API pod being killed whenever a cluster scan is started next to the container image scanning.

Another option to fix this is to still make the requests and limits a bit higher but then also have more than 1 replica of the scan API running. However, there would still be a chance to trigger multiple scans on that single instance and it might still end up being killed

**Comment by imilchev** [comment]
another option to fix this is to create a `CronJob` that just runs `mondoo scan k8s --discover container-images --all-namespaces` and not do that via the scan API at all. That might be the more feasible option for now but it is the opposite of the future plans for an autoscaling scan API that handles all scans

**Comment by imilchev** [comment]
I was thinking about this. Perhaps we shouldn't use `--all-namespaces` when running the scan as this will always result in a single scan API instance bearing all the load. Instead we could "distribute" the load a bit while still letting the Mondoo client perform all the discovery. For example, the `CronJob` that triggers the scan could start by listing all the namespaces and dispatching separate jobs for each namespace. In this way if we have more than 1 instance of the scan API, we could even parallelise the work. We would also make sure that we get the response in batches instead of one big block.

@chris-rock @joelddiaz @czunker any thoughts on this topic?

**Comment by joelddiaz** [comment]
Not being familiar with how the underlying container image scanning works, I have to ask. If we have the ScanAPI perform scans one-Namespace-at-a-time, do we then end up double/triple/whatever scanning if a Pod in NamespaceA uses containerImageX and another Pod in NamespaceB also uses containerImageX?

**Comment by imilchev** [comment]
> Not being familiar with how the underlying container image scanning works, I have to ask. If we have the ScanAPI perform scans one-Namespace-at-a-time, do we then end up double/triple/whatever scanning if a Pod in NamespaceA uses containerImageX and another Pod in NamespaceB also uses containerImageX?

yup... I forgot about this case. However, I also don't like that we now hand over this one job to a single instance and let it struggle with it for a pretty long time

**Comment by czunker** [comment]
What if we go one step further and create a scan job for each image?
- List all the images
- De-duplicate the images
- Create a scan job for each image
Does this create additional overhead?

**Comment by czunker** [comment]
@imilchev Is this still valid after your latest memory improvements?

**Comment by imilchev** [comment]
I think now it's alright. Let's close this and monitor it. If issues pop up again, we can always re-open
