### ISSUE TITLE
Cannot run integration tests for forks

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#553]
Our integration tests fail for forked repos and dependabot branches because they do not have access to the repo secrets. For now the main issue is the dependabot PRs because we cannot merge them due to the failing tests.

More info about workarounds can be found in https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544 and [here](https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot).

We use a similar approach for doing the test reporting for our integration tests. The reporting is separated into its own workflow which gets triggered once the integration tests finish. The reporting workflow then always runs from our repo and therefore has access to the repo and its secrets. We should try out and see what works for the integration tests.

**Comment by czunker** [comment]
The label has one downside: Once applied new commits will run the tests automatically.

As the first approach does not include `pull_request_target`, we might also use these:
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
And to re-approve new commits, set this:
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by joelddiaz** [comment]
> The label has one downside: Once applied new commits will run the tests automatically.
> 
> As the first approach does not include `pull_request_target`, we might also use these: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories And to re-approve new commits, set this: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule (bullet point 6)

If I'm reading this second link correctly, rather than using labels, we should just use the "Approved" state and the "unapprove if the code changed" setting for the repo?

**Comment by czunker** [comment]
This is how I currently understand this.
we have three different cases:
- Us (members of Mondoo) doing PRs => no fork, we have access to secrets
- dependabot => no fork, but no access to secrets
- external contributors => forks, no access to secrets

I think, the above settings help for the last case. But I'm not sure, we can combine them.

**Comment by joelddiaz** [comment]
I think any PR from a branch within the repo has access to secrets, unless it is the dependabot user. I feel like I read somewhere that the dependabot user has been special cased to not have access that it would otherwise have.

So I believe there is a way to re-special-case the dependabot user to restore the old dependabot behavior (from before they took away secret access). There is still the risk that a new dependency introduces code that tries to read/copy any secrets available in the workflow execution environment though...

Then there is the PR-from-a-fork case where we would want two things IIUC:
1) rather than run the Github workflows from the contents of the PR, we would run the Github workflow from the 'main' branch, and checkout the contents of the PR to test using the 'main' branch workflows.
2) block automatically running our CI/E2E tests against PRs-from-forks until a label/approval has been applied (since only members of Mondoo can apply labels/approvals), and automatically revoke the label/approval if the contents of the PR changes after the label/approval was given.

**Comment by czunker** [comment]
> There is still the risk that a new dependency introduces code that tries to read/copy any secrets available in the workflow execution environment though...

Totally agree, but I think we aren't going to solve this with these workflows. To solve this, we would need to implement something different.

> rather than run the Github workflows from the contents of the PR, we would run the Github workflow from the 'main' branch, and checkout the contents of the PR to test using the 'main' branch workflows.

As I understood `pull_request_target`, it does not only checkout the workflows of the main branch, but the complete code. This makes running tests quite useless.

Ok, so more research on how to solve this probably.

**Comment by czunker** [comment]
So, for `pull_request_target`:

> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. This event allows your workflow to do things like label or comment on pull requests from forks. Avoid using this event if you need to build or run code from the pull request.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by czunker** [comment]
> As the first approach does not include `pull_request_target`, we might also use these: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories 
>
>And to re-approve new commits, set this: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule (bullet point 6)

@benr has enabled these settings. Thanks @benr

**Comment by joelddiaz** [comment]
> As I understood `pull_request_target`, it does not only checkout the workflows of the main branch, but the complete code. This makes running tests quite useless.
> 

It makes testing changes to our workflow files a PITA for sure
