### ISSUE TITLE
Deleting a pod scans it again

### ISSUE THREAD

**Issue by tas50** [mondoohq/mondoo-operator#627]
**Describe the bug**
I created 2 pods and then deleted them, but the UI scanned the pods again:

![image](https://user-images.githubusercontent.com/1015200/197042747-c011d53f-df48-4598-9793-4f11cf96015d.png)

Clicking on one of those:
![image](https://user-images.githubusercontent.com/1015200/197042952-6c91c27a-ea10-4527-ba97-a07d4e2cd5f2.png)

**To Reproduce**
1. Add a pod
2. Delete a pod
3. See a garbage collection scan

**Expected behavior**
We shouldn't scan anything on a delete

**Comment by imilchev** [comment]
Deleting resources in Kubernetes is not an atomic action. When you delete a pod, for example, what you are actually doing is requesting the deletion of that pod. Other operations might need to happen in the background before the pod actually gets deleted.

For example, deleting a pod with a finalizer:
1. Delete pod will actually set the deletion timestamp for the pod
2. This will trigger reconciliation
3. The controller that has added the finalizer will perform an update, so the finalizer is removed
4. The pod will be deleted


This is a standard pattern in Kubernetes and it explains what you are seeing in the UI. It is not a bug. Technically we could say that the admission controller ignores all update events for workloads that are being deleted (that have their deletion timestamp set). However, I am
not sure if that makes sense. I would rather see the event as it happens.
