### ISSUE TITLE
Add health checks to Mondoo Client pods

### ISSUE THREAD

**Issue by harshaisgud** [mondoohq/mondoo-operator#63]
**Is your feature request related to a problem? Please describe.**
Current policy only checks for existence of deployment and daemonset. Needs to be extended to check if the containers have started up correctly.

**Describe the solution you'd like**
Use Mondoo to scan container runtime logs files for correct startup messages.

**Describe alternatives you've considered**
Just parse files using awk  and compare . It is cumbersome . Better to include as part of policy.

**Additional context**
Mondoo currently does not allow parsing journalctl files

**Comment by chris-rock** [comment]
@harshaisgud Can you explain why we need the journalctl for the container status? We should ask k8s directly for the status:

```
k8s.pods { name manifest["status"]["containerStatuses"] { _["started"] == true } }
```

**Comment by harshaisgud** [comment]
@chris-rock  There are cases where mondoo is running but the credentials are not correct, where the test passes but the mondoo-client is not "running". I thought it would be better to check logs than status in this case.

**Comment by chris-rock** [comment]
1. Check that credentials are valid
2. If they are not valid, the pod fail (no health check)

Add health check "exec health check" via `mondoo status`, which returns a non-zero exit code if credentials are missing or wrong. Then the pod is failing and we can implement the status check as shown above.
