### ISSUE TITLE
report the operator version as part of the last state object

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/mondoo-operator#674]
**What is not working as you expected it?**

https://github.com/mondoohq/mondoo-operator/blob/e68446ef119b421abdd039c90e1afe587b070bab/controllers/status/operator_status.go#L146

in this part of the code, the version reported (operator version) should be moved into the last state object

**Comment by imilchev** [comment]
That `Version` field seems to be exactly for reporting the agent version. Do we want to report the operator version in the state and here or do we simply move the version to the last state?

**Comment by vjeffrey** [comment]
oh, nice catch, actually we should probably have both the client version and the operator version, both in the laststate object.
