### ISSUE TITLE
E2E testing OLM deployment

### ISSUE THREAD

**Issue by jensgrnb** [mondoohq/mondoo-operator#69]
**What is is not working as you expected it?**
operator-sdk run bundle tries to pull the referenced image b4 checking local repo. 
For PRs this will always fail. 

**Where on the platform does it happen?**
mondoo-operator

**How do we replicate the issue?**
Add E2E testing with operator-sdk run bundle and you'll get a 404

**Expected behavior (i.e. solution)**
We should be able to use a local bundle image for e2e testing. 

**Other Comments**
Might be a issue on operator-sdk's github

**Comment by chris-rock** [comment]
@jensgrnb is this done via https://github.com/mondoohq/mondoo-operator/pull/131/files#diff-7df6fde7cd40d060002a40cd3e8e75083d6e02126efac835930e66eee5c4dd8dR188-R233

**Comment by jensgrnb** [comment]
Yep I belive so

**Comment by imilchev** [comment]
I guess this is done now then. Going to close the issue
