### ISSUE TITLE
GKE GCOS nodes not being scanned correctly from operator

### ISSUE THREAD

**Issue by tas50** [mondoohq/mondoo-operator#735]
**Describe the bug**
I'm not sure if this is an operator issue or a cnspec/cnquery issue, but I figured this is a good place to start. We have a few issues with GCOS right now:

1: Nodes showing as other in the OS

![image](https://user-images.githubusercontent.com/1015200/211368028-edec0ad8-c45c-4289-8c67-46d49b039a99.png)

2: Nodes have no policy being applied
![Screenshot 2023-01-09 at 9 19 19 AM](https://user-images.githubusercontent.com/1015200/211368410-54f80f10-489f-4c49-9280-51d02b659664.png)

**Comment by imilchev** [comment]
This seems to work now
