### ISSUE TITLE
Hitting GH rate limits during tests

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#736]
**Describe the bug**
```
/home/runner/work/mondoo-operator/mondoo-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go generate ./controllers/... ./pkg/... ./tests/framework/nexus/...
test -s /home/runner/work/mondoo-operator/mondoo-operator/bin/kustomize || { curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 4.5.7 /home/runner/work/mondoo-operator/mondoo-operator/bin; }
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
make: *** [Makefile:256: /home/runner/work/mondoo-operator/mondoo-operator/bin/kustomize] Error 1
```

**To Reproduce**
Looks like this does not happen every time.

**Expected behavior**
kustomize should install and tests start

**Comment by imilchev** [comment]
I believe this is because `kustomize` is pulled for every step of the pipeline. I think before it was only the case for the integration tests. Now it's needed for building and for unit tests too. Also I think the rate limit is for the organization globally, not for the repo (we need to double check that). If that's the case it means that the more actions we run, the higher the chance we run into this

**Comment by czunker** [comment]
I'm not sure which rate limit we are hitting here.

When it is the GH actions rate limit, it is:
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the person making requests.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
and
> When using GITHUB_TOKEN, the rate limit is 1,000 requests per hour per repository.

Looking further it does not seem to be clear: https://github.com/github/docs/issues/8031

Perhaps we should switch from using the script to installing kustomize by directly downloading it from the releases page. Perhaps that helps.

**Comment by czunker** [comment]
The message is created by the install script:
https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh#L140

The referenced URL is the GitHub API, so switching to releases directly should fix it.
