### ISSUE TITLE
Cloud tests fail because of panic

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#746]
**Describe the bug**
```

-----------------------------------------
CONTAINER: mondoo-k8s-scan
-----------------------------------------
2023-02-05T23:29:04Z	INFO	k8s-scan	triggering Kubernetes resources scan
2023-02-05T23:29:13Z	ERROR	k8s-scan	Kubernetes resources scan was not successful	{"error": "scan API returned not OK. &{WorstScore:<nil> Ok:false}"}
Error: scan API returned not OK. &{WorstScore:<nil> Ok:false}
Usage:
  mondoo-operator k8s-scan [flags]

Flags:
      --cleanup-assets-older-than string   Set the age for which assets which have not been updated in over the time provided should be garbage collected (eg 12m or 48h)
  -h, --help                               help for k8s-scan
      --integration-mrn string             The Mondoo integration MRN to label scanned items with if the MondooAuditConfig is configured with Mondoo integration.
      --namespaces strings                 Only resources residing in this list of Namespaces will be scanned
      --namespaces-exclude strings         Ignore resources residing in any of the specified Namespaces
      --scan-api-url string                The URL of the service to send scan requests to.
      --scan-container-images              A value indicating whether to scan container images.
      --set-managed-by string              String to set the ManagedBy field for scanned/discovered assets
      --timeout int                        The timeout in minutes for the scan request.
      --token-file-path string             Path to a file containing token to use when making scan requests.

panic: scan API returned not OK. &{WorstScore:<nil> Ok:false}

goroutine 1 [running]:
main.main()
	/home/runner/work/mondoo-operator/mondoo-operator/cmd/mondoo-operator/main.go:22 +0xab
```

**To Reproduce**

1. Run the cloud tests workflow
2. Check logs of `...client-k8s-scan` Pod
3. Note the error

**Expected behavior**
Tests should pass.

**Comment by czunker** [comment]
The panic is intended in such cases.

Perhaps this is the problem:
```
[90m2023-02-08T13:53:16Z[0m [1m[31mERR[0m[0m marketplace> failed to retrieve policy bundle from upstream [36merror=[0m[31m"rpc error: code = Unknown desc = ent: constraint failed: pq: duplicate key value violates unique constraint \"policy_bundles_mrn_key\""[0m [36mpolicy=[0m//assets.api.mondoo.app/spaces/compassionate-ptolemy-549893/assets/2LSVJCpWYSA41k1Ezc0lh4ezj1a [36mreq-id=[0mglobal
[90m2023-02-08T13:53:16Z[0m [32mINF[0m scan for asset kube-system/pdcsi-node-qg2nj (k8s-object) completed
[90m2023-02-08T13:53:16Z[0m [32mINF[0m scan for asset kube-system/pdcsi-node-qg2nj (k8s-object) completed
[90m2023-02-08T13:53:16Z[0m [1m[31mERR[0m[0m failed to synchronize asset to Mondoo Platform  [36merror=[0m[31m"rpc error: code = Internal desc = could not sync assets"[0m
```

**Comment by ET-Torsten** [comment]
We run into the same bug / error. Any solution here? Anything we are missing?

**Comment by czunker** [comment]
> We run into the same bug / error. Any solution here?
> 
> ```
> 2024-03-21T10:17:17Z	INFO	k8s-scan	triggering Kubernetes resources scan
> 2024-03-21T10:17:22Z	ERROR	k8s-scan	Kubernetes resources scan was not successful	{"error": "scan API returned not OK. &{WorstScore:<nil> Ok:false}"}
> Error: scan API returned not OK. &{WorstScore:<nil> Ok:false}
> Usage:
>   mondoo-operator k8s-scan [flags]
> 
> Flags:
>       --cleanup-assets-older-than string   Set the age for which assets which have not been updated in over the time provided should be garbage collected (eg 12m or 48h)
>   -h, --help                               help for k8s-scan
>       --integration-mrn string             The Mondoo integration MRN to label scanned items with if the MondooAuditConfig is configured with Mondoo integration.
>       --namespaces strings                 Only resources residing in this list of Namespaces will be scanned
>       --namespaces-exclude strings         Ignore resources residing in any of the specified Namespaces
>       --scan-api-url string                The URL of the service to send scan requests to.
>       --scan-container-images              A value indicating whether to scan container images.
>       --set-managed-by string              String to set the ManagedBy field for scanned/discovered assets
>       --timeout int                        The timeout in minutes for the scan request.
>       --token-file-path string             Path to a file containing token to use when making scan requests.
> 
> panic: scan API returned not OK. &{WorstScore:<nil> Ok:false}
> 
> goroutine 1 [running]:
> main.main()
> 	/home/runner/work/mondoo-operator/mondoo-operator/cmd/mondoo-operator/main.go:25 +0xa5
> ```
> 
> Anything we are missing?

Hey @ET-Torsten ,

the original issue is already solved (cloud tests no longer see this panic).

For your issue:
- Which version of the operator are you using?
- Could you please check the logs of the Scan API Pod?

**Comment by czunker** [comment]
Thanks for the update.

It's good to know that it's not always failing.

To track this down:
- Please check for OOM kills of the scan Pod. We know our default resource limits do not work with bigger clusters.
- Please check the cnspec image used in the Scan API Pod. In some cases, we experienced timeouts during scans. But cnspec received some performance improvements lately. An update may help.

**Comment by czunker** [comment]
Some more help on how to set the resources, as you can do this for different components:
https://github.com/mondoohq/mondoo-operator/blob/main/docs/user-manual.md#configure-resources-for-the-operator-and-its-components

In your case, it sounds like you might need the change the resources for the scanner aka. Scan API Pod.

**Comment by czunker** [comment]
cnspec version looks good. That's the latest.

So, we'd need to figure out the error message. We will see whether we can make this more descriptive and what's causing this.

**Comment by czunker** [comment]
Because the remaining issue has nothing to do with the initial topic of this issue, I'll close this one in favor of two new issues:
https://github.com/mondoohq/mondoo-operator/issues/1090
https://github.com/mondoohq/mondoo-operator/issues/1091
