### ISSUE TITLE
Scan API keeps crashing because of corrupted queue file

### ISSUE THREAD

**Issue by czunker** [mondoohq/mondoo-operator#852]
**Describe the bug**
The Scan API pod is in a `CrashLoopBackOff` loop. From the logs of the Pod:
```
FTL could not enable scan queue error="unable to create queue segment in /tmp/cnspec-queue/disk-queue: unable to load queue segment in /tmp/cnspec-queue/disk-queue: segment file /tmp/cnspec-queue/disk-queue/0000000000004.dque is corrupted: error reading gob data from file: EOF"
```

And the Pod is only running 32h:
```
mondoo-client-scan-api-6c9fb8d948-5dw92                           0/1     CrashLoopBackOff   183 (106s ago)   32h
```

We now saw this on our edge and demo clusters.

**To Reproduce**

1. Deploy the operator
2. Enable k8s resource scanning
3. Wait some time (This part isn't clear, how long it actually takes)
4. Note the error

**Expected behavior**
The file shouldn't get corrupted and the Pod shouldn't keep restarting.

**Desktop (please complete the following information):**

- latest mondoo-operator v1.15.2
- latest cnspec v8 image

**Aditional context**
Restarting the Pod, temporarily fixes the issue.

**Comment by imilchev** [comment]
we can swap the library that creates the queue for another solution or as a quick fix we can add an init container that will make sure the queue is deleted every time the pod restarts

**Comment by mariuskimmina** [comment]
Working on the new queue implementation here: https://github.com/mondoohq/pdque
