### ISSUE TITLE
Test and document deployment in GKE cluster

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#88]
To make it easier to use Mondoo with GKE, we want to add instruction how to deploy Mondoo into GKE.

- test setup of the operator in GKE
- document step how to best install it into GKE and add this to our `/docs`

**Comment by harshaisgud** [comment]
Can this ticket be closed @chris-rock ?

**Comment by chris-rock** [comment]
Thank you @harshaisgud
