### ISSUE TITLE
Determine requirements to publish to GKE marketplace

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#89]
Google has a public marketplace https://cloud.google.com/marketplace/docs/kubernetes-apps and Mondoo should be easy to be activated via that. We need to determine the requirements to bring the operator into the marketplace.

**Comment by lisa-noeth** [comment]
There are a few things we probably need to think about: 
https://cloud.google.com/marketplace/docs/partners/get-started#requirements

**Comment by lisa-noeth** [comment]
https://cloud.google.com/marketplace/docs/partners/develop - Overview of all supported app types in Marketplace
https://cloud.google.com/marketplace/docs/partners/kubernetes: This page details the requirements for listing k8 apps. This can be deployed through Helm or the CLI, but as container images deployed on GKE cluster.
https://cloud.google.com/marketplace/docs/partners/container: This is about deploying Open Source apps, but again containers are required.

--> Option 3 seems like a good way to move forward

**Comment by chris-rock** [comment]
Unfortunately it seems like option 3 will not work since this seems to focus on single-container apps.

**Comment by chris-rock** [comment]
We do not pursue the publication in Google Marketplace at this point.
