### ISSUE TITLE
Kubernetes resources garbage collection is not working in v9

### ISSUE THREAD

**Issue by imilchev** [mondoohq/mondoo-operator#893]
**Describe the bug**
Running the operator with the `FEATURE_ENABLE_V9` flag enabled. I can see that my kubernetes resource assets aren't getting garbage collected by the operator. I don't see any errors in the `k8s-scan` cronjob.

**To Reproduce**

1. Install the operator on a cluster
2. Enable v9
3. Create a few workloads and let the operator scan then with a cluster scan
4. Delete the workloads
5. Wait for a couple of hours and see that they are still in the UI

**Expected behavior**
Old kubernetes resources should disappear after 2h

**Screenshots or CLI Output**
![image](https://github.com/mondoohq/mondoo-operator/assets/16187050/1748c94d-d653-4110-a9e6-320ce9c798fd)

**Comment by imilchev** [comment]
Maybe the `ManagedBy` field isn't set correctly or the actual garbage collect call isn't being executed properly. I haven't investigated this further

**Comment by czunker** [comment]
Looks like https://github.com/mondoohq/cnspec/pull/895 isn't enough. I see the assets have `managedby` set, but they don't get collected. Or the 2h interval is what is currently configured. I'll check what's missing.

**Comment by czunker** [comment]
We still need to merge https://github.com/mondoohq/mondoo-operator/pull/903
