### ISSUE TITLE
Publish OLM Bundle on operator hub

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#91]
With #58 we have the operator bundle ready. As a next step, we want to release the bundle on https://operatorhub.io/?category=Security

- determine the requirements and the process to get the operator in
- prepare everything mentioned in https://operatorhub.io/contribute
- add the operator to https://github.com/k8s-operatorhub/community-operators/tree/main/operators

**Comment by chris-rock** [comment]
The redhat specific operator hub is here https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators

**Comment by harshaisgud** [comment]
Interesting so the documentation(https://k8s-operatorhub.github.io/community-operators/contributing-where-to/) has not been updated then.

**Comment by chris-rock** [comment]
Initial work has been done via https://github.com/k8s-operatorhub/community-operators/pull/851 I am going to split out the redhat specific operator into its own ticket
