### ISSUE TITLE
Test and document deployment into EKS

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#92]
To make it easier to use Mondoo with Amazon EKS, we want to add instruction how to deploy Mondoo into EKS.

- test setup of the operator in EKS
- document step how to best install it into EKS and add this to our `/docs`

**Comment by harshaisgud** [comment]
Tested to work on EKS clusters at version 1.21

**Comment by harshaisgud** [comment]
Can this be closed @chris-rock ?

**Comment by chris-rock** [comment]
Thank you @harshaisgud
