### ISSUE TITLE
cronjobs failing with: cannot find field 'family' in platform

### ISSUE THREAD

**Issue by renanqts** [mondoohq/mondoo-operator#927]
**Describe the bug**
cronjob for nodes and containers-scan are constantly failing with the output:
```
error: rpc error: code = Unknown desc = failed to compile query: failed to compile query 'platform.family.contains(_ == 'linux') || platform.family.contains(_ == 'windows') || platform.name == "vmware-esxi" || platform.name == "vmware-vsphere"
': failed to compile: failed to compile: failed to compile: cannot find field 'family' in platform
```

**To Reproduce**

Install the operator in an EKS cluster using Bottlerocket AMI.

**Expected behavior**
It should just work with the current spec policy already defined in the job.

**Versions (please complete the following information):**

- OS: Linux Bottlerocket
- OS Version: 1.15.0 (aws-k8s-1.27)
- Helm chart version: 1.13.2 (1.17.1 was also tested without success)

**Additional context**
I'm not sure if it should be an issue for the operator, but since we can configure cnspec filter policies, I suppose it should be here.
Another [PR](https://github.com/mondoohq/cnspec/pull/838) fixed it in another place, but it could be a possible fix as well here

**Comment by imilchev** [comment]
This seems to be caused by an outdated policy. Do you have any custom policies enabled in your space? I'm happy to jump in a call and look at it together

**Comment by renanqts** [comment]
Hey @imilchev 

as fair as I check, no. Please, let's do this call so.

**Comment by imilchev** [comment]
Please join our Slack community so we can chat there and solve the issue. I mailed you a link
