### ISSUE TITLE
Define required metrics to expose it for prometheus

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/mondoo-operator#94]
- research best patterns from known operators
- define the metrics that are applicable for mondoo
- add logic to collect the metrics to the operator

**Comment by chris-rock** [comment]
As with the web hook implementation, we do not expect Prometheus to be installed. The user defines prometheus in the MondooAuditConfig and the operator sets up the required values.

**Comment by harshaisgud** [comment]
I am working on a service monitor implementation.Should I also create a prometheus instance ? All of the operators that I am looking at for examples only setup servicemonitor and leave prometheus setup to the end user. Is this something we want to address?

**Comment by chris-rock** [comment]
It needs to be written in a way that prometheus is not required.

**Comment by harshaisgud** [comment]
Prometheus is required . There is no getting around that.

**Comment by chris-rock** [comment]
@joelddiaz Can you write down how this should be done, I think we want to use the same approach as with cert-manager where we do not require it

**Comment by joelddiaz** [comment]
Yes. Prometheus is required for the metrics collection to work. But we shouldn't require that a user must have metrics collection with Prometheus enabled. So we can have an enabled/disabled flag in the MondooAuditConfig to control whether or not the mondoo-operator creates the ServiceMonitor resource, but the mondoo-operator will not setup/install Prometheus.

I view this similar to how a user of the Webhooks has several choices when it comes to the TLS certificates for the webhook server/pod. The user can make their own TLS certificates and put them in a Secret that the webhook will use. The user can say "I already have cert-manager installed, so mondoo-operator just needs to tell cert-manager to create the TLS secrets". Or the user can say "I'm running on OpenShift, so mondoo-operator just needs to tell OpenShift to create the TLS secrets".

For the Prometheus/metrics work for this card, we should have the metrics/ServiceMonitor disabled by default, and (for example) when a user sets MondooAuditConfig.Spec.Metrics.Enabled to 'true', the mondoo-operator will create the ServiceMonitor resource (and just assume that Prometheus has been installed on the cluster already).

Hope that makes some sense.

**Comment by harshaisgud** [comment]
That makes perfect sense. I really wasnt sure about not even having prometheus installed. Prometheus is a requirement for the serviceMonitor to work.
